### ISSUE TITLE
Something ...

### ISSUE THREAD

**Issue by 1and1is3** [Sid72020123/scProxy#1]
First of all; this is not a real error, more like a limitation.

If you make a request to an api page with '?' or '&' characters, such as `https://api.scratch.mit.edu/users/programORdie/followers/?limit=40&offset=0`, it fails. 
I have no idea how you're going to fix it, but I'm guessing you'll figure something out.

**Comment by Sid72020123** [comment]
Oh. This is actually the out-dated version of the proxy.

I forgot to mention that the new proxy code is shifted to the ScratchConnect repo: https://github.com/Sid72020123/scratchconnect/tree/main/scAdditionalAPIs/free-proxy

And that proxy works: https://apis.scratchconnect.eu.org/free-proxy/get?url=https://api.scratch.mit.edu/users/griffptch/followers/?limit=5&offset=0

**Comment by 1and1is3** [comment]
I used the link you said, but it didn't work. Now I click on this link and it does work. Strange...

**Comment by Sid72020123** [comment]
Hmm... That's strange...

**Comment by 1and1is3** [comment]
Yeah, maybe I had just made a typo, but that seems unlikely.
